config/routes.rb
Rails.application.routes.draw do
  resources :table_reservations

  root 'table_reservations#index'

end

app/models/table_reservation.rb
class TableReservation < ActiveRecord::Base
  self.table_name = :reservations

  validates :start_time, :end_time, :table_number, presence: true
  validates :table_number, numericality: { only_integer: true, greater_than: 0 }
  validate :correct_datetimes_passed
  validate :timeframe_is_free

private

  def correct_datetimes_passed
    self.errors[:start_time] << "must be a valid date" unless DateTime.parse(self.start_time) rescue false
    self.errors[:end_time] << "must be a valid date" unless DateTime.parse(self.end_time) rescue false

    self.errors[:end_time] << "should be greater than a start date" unless (self.end_time > self.start_time) rescue false
  end

  def timeframe_is_free
    tr = TableReservation
        .where('table_number = ?', self.table_number)
        .where('(DATEDIFF(start_time, ?) * DATEDIFF(?, end_time)) >= 0', self.end_time, self.start_time)
        .where('NOT ((start_time > ?) OR (end_time < ?))', self.end_time, self.start_time)

    tr = tr.where('id != ?', self.id) if self.id

    puts tr.to_sql
    puts self.id.to_yaml
    puts tr.first.to_yaml
    is_free = tr.count == 0

    self.errors[:base] << 'This time may not be reserved due to the existing reservations' unless is_free
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/table_reservations_controller.rb
class TableReservationsController < ApplicationController
  before_action :set_table_reservation, only: [:show, :edit, :update, :destroy]

  # GET /table_reservations
  # GET /table_reservations.json
  def index
    @table_reservations = TableReservation.all
  end

  # GET /table_reservations/1
  # GET /table_reservations/1.json
  def show
  end

  # GET /table_reservations/new
  def new
    @table_reservation = TableReservation.new
  end

  # GET /table_reservations/1/edit
  def edit
  end

  # POST /table_reservations
  # POST /table_reservations.json
  def create
    @table_reservation = TableReservation.new(table_reservation_params)

    respond_to do |format|
      if @table_reservation.save
        format.html { redirect_to @table_reservation, notice: 'Table reservation was successfully created.' }
        format.json { render :show, status: :created, location: @table_reservation }
      else
        format.html { render :new }
        format.json { render json: @table_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /table_reservations/1
  # PATCH/PUT /table_reservations/1.json
  def update
    respond_to do |format|
      if @table_reservation.update(table_reservation_params)
        format.html { redirect_to @table_reservation, notice: 'Table reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @table_reservation }
      else
        format.html { render :edit }
        format.json { render json: @table_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /table_reservations/1
  # DELETE /table_reservations/1.json
  def destroy
    @table_reservation.destroy
    respond_to do |format|
      format.html { redirect_to table_reservations_url, notice: 'Table reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table_reservation
      @table_reservation = TableReservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_reservation_params
      params.require(:table_reservation).permit(:start_time, :end_time, :table_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/table_reservations_helper.rb
module TableReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/table_reservations/_form.html.haml
= form_for @table_reservation do |f|
  - if @table_reservation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@table_reservation.errors.count, "error")} prohibited this table_reservation from being saved:"
      %ul
        - @table_reservation.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .field
    = f.label :end_time
    = f.datetime_select :end_time
  .field
    = f.label :table_number
    = f.number_field :table_number
  .actions
    = f.submit 'Save'

app/views/table_reservations/edit.html.haml
%h1 Editing table_reservation

= render 'form'

= link_to 'Show', @table_reservation
\|
= link_to 'Back', table_reservations_path

app/views/table_reservations/index.html.haml
%h1 Listing table_reservations

%table
  %thead
    %tr
      %th Start time
      %th End time
      %th Table number
      %th
      %th
      %th

  %tbody
    - @table_reservations.each do |table_reservation|
      %tr
        %td= table_reservation.start_time
        %td= table_reservation.end_time
        %td= table_reservation.table_number
        %td= link_to 'Show', table_reservation
        %td= link_to 'Edit', edit_table_reservation_path(table_reservation)
        %td= link_to 'Destroy', table_reservation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Table reservation', new_table_reservation_path

app/views/table_reservations/new.html.haml
%h1 New table_reservation

= render 'form'

= link_to 'Back', table_reservations_path

app/views/table_reservations/show.html.haml
%p#notice= notice

%p
  %b Start time:
  = @table_reservation.start_time
%p
  %b End time:
  = @table_reservation.end_time
%p
  %b Table number:
  = @table_reservation.table_number

= link_to 'Edit', edit_table_reservation_path(@table_reservation)
\|
= link_to 'Back', table_reservations_path